<a href="https://colab.research.google.com/github/Odeyiany2/ACCESS-6.0-Skills-Acquisition-Program-Data-Science/blob/main/week%204/Week_4_Feature_Engineering_and_Model_Thinking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Feature Engineering, Encoding, Normalization, Pipelines, Model Thinking**

**Objectives**

* Perform categorical encoding and normalization.

* Discuss how engineered features improve model performance.

* Supervised vs unsupervised learning concepts.

* Walkthrough a simple regression example (conceptual).

* Introduce mini-capstone: cleaning, EDA, feature engineering, model recommendation (no training).

### **1. What is Feature Engineering?**

Feature engineering is the process of transforming raw data into meaningful inputs that machine learning models can understand.

Examples:
- Creating `month` from a `date`
- Grouping categories (e.g., “Card”, “Cash”, “Transfer” → Payment Mode)
- Aggregating transactions (daily / monthly spend)

**Key idea:**  
Good features = better models.

## **2. Feature Creation vs Feature Engineering**

You have already done **feature creation**:
- Extracting day, month, year
- Creating total spend per category

**Feature engineering goes further**:
- Preparing features *specifically for models*
- Encoding text into numbers
- Scaling numeric values

### **3. Why Models Need Preprocessing?**

Machine learning models:
- ❌ Cannot understand text
- ❌ Can be biased by scale (₦10 vs ₦10,000)
- ✅ Work best with clean, numeric, comparable features

### **4. Encoding Categorical Variables (Concept)**

**Encoding** converts text categories into numbers.

Examples:
- Category → Food, Rent, Transport
- Location → Lagos, Abuja, Ibadan

Why?
> Models only understand numbers, not words.

Many encoding techniques -> OneHotEncoder, LabelEncoder


Python Libraries -> Scikit Learn (Python's Machine Learning library)

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from google.colab import drive

In [ ]:
df  = pd.DataFrame({"category": ["food", "rent", "transport"], "amount": ["2000", "3000", "50000"]})
df.head()

    category amount
0       food   2000
1       rent   3000
2  transport  50000

In [ ]:
#converting the categorical column using LabelEncoder

encoder = LabelEncoder()
df["category"] = encoder.fit_transform(df["category"])
df.head()

   category amount
0         0   2000
1         1   3000
2         2  50000

In [ ]:
#using a onehotencoder instead
df_new = pd.DataFrame({"category": ["food", "rent", "transport"], "amount": ["2000", "3000", "50000"]})
df_new.head()

    category amount
0       food   2000
1       rent   3000
2  transport  50000

In [ ]:
#using a onehotencoder instead
cat_cols = ["category"]
one = OneHotEncoder()
encoded = one.fit_transform(df_new[["category"]])
encoded = pd.DataFrame(encoded.toarray(), columns = one.get_feature_names_out(cat_cols))
encoded.head()

   category_food  category_rent  category_transport
0            1.0            0.0                 0.0
1            0.0            1.0                 0.0
2            0.0            0.0                 1.0

In [ ]:
df_2 = pd.DataFrame({"category": ["food", "rent", "transport"], "amount": ["2000", "3000", "50000"]})
encoded_df = pd.get_dummies(df_2, columns = ["category"])
encoded_df.head()

  amount  category_food  category_rent  category_transport
0   2000           True          False               False
1   3000          False           True               False
2  50000          False          False                True

### **5. Normalization / Scaling (Concept)**

Scaling ensures numeric columns are on similar ranges.

Why?
- Models are sensitive to magnitude
- Large values can dominate smaller ones

Common scalers:
- StandardScaler
- MinMaxScaler

In [ ]:
df.head()

   category amount
0         0   2000
1         1   3000
2         2  50000

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler()
df["amount"] = scaler.fit_transform(df[["amount"]])
df.head()

   category    amount
0         0 -0.729315
1         1 -0.684663
2         2  1.413979

In [ ]:
#using MinMaxScaler
scaler_2 = MinMaxScaler()
df_new["amount"] = scaler_2.fit_transform(df_new[["amount"]])
df_new.head()

    category    amount
0       food  0.000000
1       rent  0.020833
2  transport  1.000000

### **6. Intro to Pipelines (High-Level)**

A pipeline helps:
- Apply preprocessing steps in order
- Avoid data leakage
- Keep workflows clean and repeatable

Think of it like:
Raw Data → Cleaning → Encoding → Scaling → Model

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
numeric_cols = ["amount"]
categorical_cols = ["category"]

#preprocessing steps in one -> encoding, scaling/normalization
preprocessor = ColumnTransformer(
    transformers = [("num", StandardScaler(), numeric_cols),
                    ("cat", OneHotEncoder(drop = "first"), categorical_cols)]
)


#putting it into a pipeline
pipe = Pipeline(steps = [("preprocessor", preprocessor)])

In [ ]:
#create a new dataset
df_3 = pd.DataFrame({"category": ["food", "rent", "transport"], "amount": ["2000", "3000", "50000"]})


#apply pipeline to the data
df_3 = pipe.fit_transform(df_3)
df_3

array([[-0.72931526,  0.        ,  0.        ],
       [-0.68466331,  1.        ,  0.        ],
       [ 1.41397857,  0.        ,  1.        ]])

### **7. Intro to Model Thinking (No Training Yet)**

Before choosing a model, always ask:

1. What is the target variable?
2. Is it numeric or categorical?
3. Does this look like:
   - Regression? -> numeric target variable
   - Classification? -> categorical target variable
   - Clustering? -> No target variable (Unsupervised Learning)

Supervised, Unsupervised and Reinforcement Learning

supervised Learning -> Features (Independent Variable) + Target Variables (dependent variable)

Unsupervised Learning -> Only features

Reinforcement Learning -> rewards + penalties (punishments) Reinforcement Learning (RL) is a machine learning case  where an agent learns to make decisions by interacting with an environment, receiving rewards or penalties, and optimizing its actions over time.

We will start actual model building in **January**.


[Scikit Learn](https://scikit-learn.org/stable/index.html)

### **8. Mini Project Overview (Preview)**

You will receive a **2-part mini project**:

### Part 1
- Apply preprocessing ideas to the dataset you've been working one [🏪 Warehouse and Retail Sales Montgomery County](https://www.kaggle.com/datasets/samanfatima7/warehouse-and-retail-sales-montgomery-county)

### Part 2
- Explore a new dataset - [Supermarket Dataset](https://www.kaggle.com/datasets/mustofaahmad/inventory-management-grocery-industry)
- Decide:
  - What features matter?
  - What preprocessing is needed?
  - What model *should* be built?

Mini Project Details - [Click Here](https://github.com/Odeyiany2/ACCESS-6.0-Skills-Acquisition-Program-Data-Science/blob/main/week%204/Mini%20Project.md)