## **Session 3 — Pandas I: Reading & Inspecting Data**

Instructor Dataset - [Budgetwise Finance Dataset](https://www.kaggle.com/datasets/mohammedarfathr/budgetwise-personal-finance-dataset)

This notebook demonstrates how to load, inspect, and do basic filtering & grouping using **pandas**.


### **Pandas Overflow**
Read -> Inspect -> Clean -> Transform -> Model the data.


### **Reading and Inspecting Methods**
1. head

head displays the first few rows of the dataset.
It helps you quickly see how the data looks — the structure, sample entries, and whether columns loaded correctly.

2. tail

tail shows the last few rows of the dataset.
It is useful for checking the end of the file, especially when the data may have inconsistencies or formatting issues at the bottom.

3. columns

columns lists the names of every column in the dataset.
This helps you understand the features available, confirm correct spelling, and identify which columns you want to work with.

4. info

info provides a full summary of the dataset, including:

number of rows and columns

each column’s data type

whether a column has missing values

memory usage

It is one of the most important inspection tools because it tells you the structure and health of your dataset.

5. shape

shape shows the size of your dataset in the form (number of rows, number of columns).
This helps you understand how large your dataset is and whether it loaded correctly.

6. describe

describe gives statistical summaries for all numerical columns, including:

average

standard deviation

minimum

maximum

percentiles

It helps you see the distribution and characteristics of your numeric data.

7. loc

loc is used to select data by labels — meaning you use actual row names or column names.
It is intuitive when you want to pick data based on column names or apply conditions (e.g., selecting all rows where Category is “Food”).

_**code example: df_loc = df.loc[df["Category"] == "Food", ["Date", "Amount"]]**_

8. iloc

iloc selects data by position — meaning you use row numbers and column numbers.
It works like selecting items in a list using their index, starting from zero.

_**code example: df_iloc = df.iloc[0:5, 0:3]  # first 5 rows, first 3 columns**_

9. Filtering

Filtering is the process of selecting rows based on a condition.
For example, you might filter:

all transactions greater than a certain amount

all records belonging to a specific category

all rows in a date range

Filtering helps narrow down the dataset to what is relevant for analysis.

_**code example: df_filtered = df[df["Amount"] > 1000]**_

10. Aggregation

Aggregation means combining or summarizing data.
Examples include calculating:

total spending per category

average amount per month

number of transactions per account

Aggregation is often done using grouping, and it helps you create insights from raw data by summarizing patterns and trends.

_**code example: df_agg = df.groupby("Category")["Amount"].sum()**_

In [1]:
import pandas as pd

In [2]:
#read the data
df_fin = pd.read_csv("/content/budgetwise_finance_dataset (1).csv")

#if it was an excel file
#df_fin = pd.read_excel(".xlxs")

In [23]:
#inspecting the data

# - head(): first 5 rows of this dataset
df_fin.head()

,transaction_id,user_id,date,transaction_type,category,amount,payment_mode,location,notes
0,T4999,U018,2023-04-25,Expense,Educaton,3888,card,Ahmedabad,Movie tickets
1,T12828,U133,08/05/2022,Expense,rent,649,NaN,Hyderabad,asdfgh
2,T7403,U091,31-12-23,Income,Freelance,13239,Csh,BAN,Books
3,T12350,U097,NaN,Expense,Fod,6299,Bank Transfer,AHMEDABAD,Electricity bill
4,T7495,U088,10/28/2022,Expense,entertainment,2287,CARD,Hyderabad,NaN

In [25]:
#inspect the last five rows
df_fin.tail()

,transaction_id,user_id,date,transaction_type,category,amount,payment_mode,location,notes
15895,T7467,U033,21-07-24,Expense,Rnt,7335,Upi,hyderabad,Coffee
15896,T7486,U142,27-02-24,Expense,Educaton,4353,card,BANGALORE,NaN
15897,T13247,U001,03/04/2024,Expense,food,1048,CRD,BANGALORE,Train ticket
15898,T13301,U147,2022-07-09,Income,Others,621176,CARD,CHENNAI,Restaurant dinner
15899,T8679,U044,08/04/2022,Expense,Utlities,5459 INR,CARD,MUM,Gym membership

In [28]:
#to get specific rows using their label positions
df_fin.iloc[8000:10000]

,transaction_id,user_id,date,transaction_type,category,amount,payment_mode,location,notes
8000,T0137,U099,11/02/2023,Expense,Rnt,1454,Csh,KOLKATA,Petrol
8001,T3984,U097,12/16/2021,Expense,Entertainment,4331,Cash,hyderabad,NaN
8002,T9431,U139,20-08-22,Expense,FOOD,₹6007,Crd,Jaipur,Movie tickets
8003,T2375,U125,2022-12-24,Expense,Others,₹9581,Bank Transfr,delhi,Petrol
8004,T11684,U045,23-02-23,Expense,Food,3690,CARD,pune,Internet bill
...,...,...,...,...,...,...,...,...,...
9995,T10318,U029,03-11-21,Expense,SAVINGS,NaN,UPI,lucknow,Monthly rent payment
9996,T12246,U097,2024-10-07,Expense,TRAVEL,5548,Bank Transfr,Lucknow,Monthly rent payment
9997,T3736,U078,07/15/2023,Expense,Entertainment,9781,UPi,Pune,Books
9998,T0340,U098,2023-10-02,Expense,Helth,7693,UPi,KOLKATA,!!!
9999,T3431,U116,2022-12-29,Expense,Utility,3306,CARD,MUM,Medicine

In [7]:
#inspect the shape
df_fin.shape
print(f"The shape of the dataset is:{df_fin.shape}")

The shape of the dataset is:(15900, 9)

In [8]:
#check the columns
df_fin.columns

Index(['transaction_id', 'user_id', 'date', 'transaction_type', 'category',
       'amount', 'payment_mode', 'location', 'notes'],
      dtype='object')

In [9]:
#checking for missing values in the dataset
df_fin.isnull().sum()

transaction_id         0
user_id                0
date                 486
transaction_type       0
category             285
amount               291
payment_mode         808
location            1262
notes               2821
dtype: int64

In [11]:
#summary statistics
df_fin.describe().T

                  count unique               top   freq
transaction_id    15900  14000             T8639      5
user_id           15900    150              U036    136
date              15414   5025        2024-08-13     14
transaction_type  15900      2           Expense  13517
category          15615     46              FOOD    583
amount            15609  11165            999999     80
payment_mode      15092     19               UPI    939
location          14638     40               PUN    398
notes             13079     26  Electricity bill    561

In [12]:
#inspecting the datatype
df_fin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15900 entries, 0 to 15899
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    15900 non-null  object
 1   user_id           15900 non-null  object
 2   date              15414 non-null  object
 3   transaction_type  15900 non-null  object
 4   category          15615 non-null  object
 5   amount            15609 non-null  object
 6   payment_mode      15092 non-null  object
 7   location          14638 non-null  object
 8   notes             13079 non-null  object
dtypes: object(9)
memory usage: 1.1+ MB

In [19]:
df_fin.head()

,transaction_id,user_id,date,transaction_type,category,amount,payment_mode,location,notes
0,T4999,U018,2023-04-25,Expense,Educaton,3888,card,Ahmedabad,Movie tickets
1,T12828,U133,08/05/2022,Expense,rent,649,NaN,Hyderabad,asdfgh
2,T7403,U091,31-12-23,Income,Freelance,13239,Csh,BAN,Books
3,T12350,U097,NaN,Expense,Fod,6299,Bank Transfer,AHMEDABAD,Electricity bill
4,T7495,U088,10/28/2022,Expense,entertainment,2287,CARD,Hyderabad,NaN

In [20]:
df_fin["date"] #this is supposed to be a datetime datatype

0        2023-04-25
1        08/05/2022
2          31-12-23
3               NaN
4        10/28/2022
            ...
15895      21-07-24
15896      27-02-24
15897    03/04/2024
15898    2022-07-09
15899    08/04/2022
Name: date, Length: 15900, dtype: object

In [13]:
#basic filtering and selection - keys are the columns
df_fin["amount"]

0            3888
1             649
2           13239
3            6299
4            2287
           ...
15895        7335
15896        4353
15897        1048
15898      621176
15899    5459 INR
Name: amount, Length: 15900, dtype: object

In [16]:
#using .loc to get the entire row for a particular column
df_fin.loc[:, ["amount"]]

         amount
0          3888
1           649
2         13239
3          6299
4          2287
...         ...
15895      7335
15896      4353
15897      1048
15898    621176
15899  5459 INR

[15900 rows x 1 columns]

In [21]:
#selecting more than one column
df_fin.loc[:, ["amount", "category"]]

         amount       category
0          3888       Educaton
1           649           rent
2         13239      Freelance
3          6299            Fod
4          2287  entertainment
...         ...            ...
15895      7335            Rnt
15896      4353       Educaton
15897      1048           food
15898    621176         Others
15899  5459 INR       Utlities

[15900 rows x 2 columns]

In [17]:
df_fin.columns

Index(['transaction_id', 'user_id', 'date', 'transaction_type', 'category',
       'amount', 'payment_mode', 'location', 'notes'],
      dtype='object')

In [18]:
#grouping and aggregate - `groupby`

df_fin.groupby("category")["amount"].sum()

category
Bonus            621933414549639Rs.1424932789573583356544932676...
EDU              3110Rs.575624978869531239858590358828165734913...
Education        222897257397 INR820454493589806₹2274₹960127159...
Educaton         388812063150530579418716389156428201₹93498729₹...
Entertain        10044114199878452371006Rs.31598839Rs.73937010$...
Entertainment    703818009939₹771346388152₹66997183218641676832...
Entrtnmnt        3143$47195542809396359883 INR77734253615978942...
FOOD             2225107 INR10733802₹78499999998174864021304265...
Fod              6299$83806197591816418687655251115742072939984...
Food             898445230852252637₹26157752033₹498Rs.107848164...
Foodd            3865126342772163276376222324549301442620173021...
Foods            416822069999992353047Rs.8644252778₹28553143765...
Freelance        1323925143101837007523852323812350450009116501...
HEALTH           52522134670739295749₹997961131008$740$73165833...
Health           68692143$63218548₹11507691790069549944₹2407848...
Helth            849794082603595813368122₹984875768131799538710...
Investment       19947₹32146462194403175822311837383029235₹7463...
Misc             49523685604142903226993₹6136237210871242398954...
OTHERS           2163₹1799716412758431397434748670Rs.7781₹49895...
Other            73004883106028769734₹9387369₹45126136512640506...
Others           595434968348233219571734726220156$131316610417...
RENT             $76194641 INR3569458315185935648428759883221$9...
Rent             2377634984432522334027792Rs.355882820712484216...
Rentt            2376072172050942078₹21771474732137612435408131...
Rnt              81822966₹61412979$6756₹55829348$675628245549Rs...
SAVINGS          8861816182316682Rs.83828475787288307452106609R...
Salary           62061855881₹41573$24920666787069378532₹5658163...
Saving           51957734799880063444₹5377Rs.621499999999973795...
Savings          52776027₹4694308487737676₹20593478839387732910...
TRAVEL           96816691₹97503942475₹67999675$2963785855238840...
Traval           1643₹9999999800 INR29851409₹9364383377481115₹5...
Travel           ₹255324078241988855249154Rs.44279053Rs.8305$18...
Travl            4286$7135₹70402082553577613841621 INR702061707...
Utilities        3520492399962607296₹33258421420642185925$4041₹...
Utility          $42623367670488417391223063247821₹9476392941₹6...
Utilties         ₹5070999999999Rs.5554527445157906908₹7838₹1686...
Utlities         5767601₹4215₹63167080₹3414Rs.98596348815896981...
education        Rs.8288119₹41893150$731563041002 INR20537121Rs...
entertainment    228737196483121356$823023982923 INR89435011256...
food             7406₹5576677₹81246502268350225811529297842247R...
health           4846977127213150₹4201$3790160654476626$2104343...
others           394149559999994153$4833₹5063$86973630₹35408221...
rent             649956730101380 INR85792962₹988Rs.677943317335...
savings          8111₹43288634505973925743615134135081791676635...
travel           8283Rs.97052135301198913308592₹469234291037364...
utilities        108166718479315922886278₹924549587818471344948...
Name: amount, dtype: object

In [ ]:
#grouping and aggregating with multiple metrics
df_fin.groupby("category")["amount"].agg(["sum", "mean", "max", "count"])


#this will fail because our dataset is highly messy

## **Assignment**

To be submitted before the next class in the [submission sheet](https://docs.google.com/spreadsheets/d/1uIpd_jGrRRlQ1X9wx3XDzakWtKQ_cWMi7gB8eaQvXrs/edit?usp=sharing) under week two session one.

You are expected to push your notebook to your github repo and submit the link to it. Your notebook should be saved as like this:

`Week 2 - Session 3; Data Handling 1 Assignment`

Using this dataset from kaggle (which you are to download) [Warehouse and Retail Sales Montgomery County](https://www.kaggle.com/datasets/samanfatima7/warehouse-and-retail-sales-montgomery-county), implement the following:

### **Part 1: Reading & Inspecting Your Dataset (Very Important)**

1. Load your dataset into a pandas DataFrame using pd.read_csv() or the correct method for your file type.

2. Use the following inspection methods and answer the accompanying questions:

   *  `df.head()`  - Question: What are the first 3 things you notice in your dataset?
   * `df.tail()` - Question: Are there any unusual patterns in the last few rows?
   * `df.info()` - Questions: How many rows and columns do you have?, Which columns have missing values?, What are the data types of each column?
   * `df.describe()` - Question: Which numerical column has the highest mean?, Which column has an unusually high maximum or a suspicious minimum?
   
   * `df.columns and df.shape` - Question: List all column names. What is the full size of your dataset?




### **Part 2: Column Selection & Basic Filtering**

Perform the following tasks and paste your code + result:

A. Selecting Columns

Select any two numerical columns and display them.

Select any two categorical columns and display them.

B. Filtering Rows

- Filter rows using one condition — for example:

   Income > 50,000

   Age < 25

   Rating == 5
  (Choose any condition that fits the dataset.)

- Filter rows using two conditions (using & or |).
  Example: customers who are Female and spent above 10,000.

  Use .loc[] to:

    - Filter a set of rows

    - Display only 2–3 selected columns for those rows.

C. Using .iloc[]

- Use .iloc[] to display:

- The first 5 rows and first 3 columns

- Rows 10–20 and columns 2–4


### **Part 3: Grouping & Aggregation (Critical Skill)**

- Use groupby() on one categorical column in your dataset.

- Choose any questions that make sense for your data:

A. Aggregation (one metric)

- Calculate the total of a numerical column for each category.
Example: Total amount spent per category.

B. Aggregation (multiple metrics)

- Use .agg() to calculate two or three metrics such as:

     - sum

     - mean

     - max

     - count

- Example:
“For each product category, calculate the total, average, and maximum transaction amount.”

C. Interpretation (very important)
  - In 3–4 sentences, write your interpretation of the results.
(What does this tell you about the dataset?)